language: python
python:
    - "3.8"
install:
    - pip install -r requirements.txt .
    - pip install pytest pytest-xdist
    - pip install pytest-cov coveralls
script:
    - pytest -n 4 --cov=src/xprmind/
after_success:
  - coveralls
